# Generated by Django 4.2.30 on 2026-06-28 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted_with_unsigned_entries', 'Submitted With Unsigned Entries'), ('submitted_fully_signed', 'Submitted Fully Signed')], max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pdf_file', models.FileField(upload_to='timesheet_pdfs/submissions/')),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('week_end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('partially_signed', 'Partially Signed'), ('fully_signed', 'Fully Signed'), ('submitted_with_unsigned_entries', 'Submitted With Unsigned Entries'), ('submitted_fully_signed', 'Submitted Fully Signed')], default='draft', max_length=50)),
                ('admin_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='timesheet_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nanny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_timesheets', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet', to='timesheets.timesheetsubmission')),
            ],
            options={
                'ordering': ['-week_start_date', '-created_at'],
                'unique_together': {('nanny', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('family_name', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('signature_status', models.CharField(choices=[('unsigned', 'Unsigned'), ('signed', 'Signed'), ('signature_invalidated', 'Signature Invalidated')], default='unsigned', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timesheets.weeklytimesheet')),
            ],
            options={
                'ordering': ['work_date', 'start_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ParentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='signatures/')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('approved_snapshot', models.JSONField(blank=True, default=dict)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_signature', to='timesheets.timeentry')),
            ],
        ),
    ]
